### ISSUE TITLE
error in generation of MomentumDifferenceVertex vertices

### ISSUE THREAD

**Issue by wkotlarski** [FlexibleSUSY/FlexibleSUSY#115]
@uukhas, @Expander: There seems to be a problem with SSV vertices when both scalars are identical. The generated vertices look, for example, like this

```c++
MomentumDifferenceVertex VertexImpl<fields::hh, fields::hh, fields::VZ>::evaluate(
   const std::array<int, 0>& indices, const context_base& context)
{
   int minuend_index = 0;
   int subtrahend_index = 0;

   const std::complex<double> result = 0;

   return {result, minuend_index, subtrahend_index};
}
```

This then causes a runtime error because we never call a vertex with 00 combination. Those vertices work fine for complex scalars so I'm guessing the error is in part of @iolojz code that looks for a position of a field in SARAH vertex. If it's done just by name, then same index will be returned twice for real scalars. I'll look for a fix.

EDIT: I'm an idiot. I think there is no Zhh coupling in the SM. Only ZAh exists. The question remains. How should we treat such vertices which are 0 when the calling code cannot know if the vertex does or does not exist. Should we just override the creating code and write
```c++
   int minuend_index = 1;
   int subtrahend_index = 0;
   const std::complex<double> result = 0;
```

EDIT2: @uukhas, I don't know how is it with your code, but the problem can be solved trivially by not generating diagrams with vertices which are identically 0. Does this error only comes from my code? I yes then it's fine because that part was done quick and dirty and I didn't filter out all necessary diagrams.

**Comment by wkotlarski** [comment]
@Expander, @pathron, I talked with @uukhas. There's a decision to be made. Should we ever write to `c++` code vertices which are identically `0` or should we force 'users' of vertices to not generate diagrams which will be obviously 0. The problem that @uukhas encountered was cause by some old code which did generate some diagrams but did not remove ones which where 0 so then it requested vertices which are 0 at `c++` level. This caused a problem because for momentum difference vertex you cannot read of the momenta to which the vertex is proportional (because it's 0) so the `c++` vertex had an information that it's proportional to the momentum of particle `0` - the momentum of particle `0` while the calling code actually supplied correct indices.

**Comment by Expander** [comment]
Many thanks for investigating!

In my opinion we should avoid such code to be generated in the first place, because then the compiler has less work to do.

Would you mind preparing a patch to achieve that?

**Comment by pathron** [comment]
Yeah i agree with Alex that the old code should be patched to avoid generating such diagrams. if this is possible in all cases we should just do that.

**Comment by wkotlarski** [comment]
Do we have a function that checks if vertex is identically 0? If not, then I propose to have a function `VertexZeroQ` with signature `VertexZeroQ[fields_List]` that `SortCp` fields and then checks for 0 depending on the type of fields. This will be slightly messy because `SARAH` doesn't have fixed format for vertices. So `FFV` vertex has to be checked differently than the `SSS` one and so on. After that this filter can be inserted in one place in @iolojz code.

**Comment by dhjjacob** [comment]
@wkotlarski @Expander @pathron There seems to be an additional issue with the generation of indices for the SSV vertex.  Specifically, when dealing with a vertex stuctured as `{conj[Sp],Sp,VP}`, where `Sp` is the incoming scalar, and `conj[Sp]` is the outgoing scalar. 

FlexibleSUSY searches for the position of the incoming and outgoing scalar fields using the Position[] function.  The position minus one of the incoming and outgoing fields in the vertex will be returned as their corresponding indices.  However, since `Sp` is technically nested in `conj[Sp]`, there are two positions returned for the incoming scalar.  The code simply takes the first occurence as the position of the field.  This means the position of the field `conj[Sp]` is erroneously returned as the position of the field `Sp`.  For comparison, the vertex  involving the fields `{Hp,conj[Hp],VP}` does not have this issue, since the field `Hp` comes first in the array, its correct position is returned.

This issue with return the position of `conj[Sp]` as the position of the `Sp` means that both the incoming and outgoing scalars have the same index, which causes an error as @wkotlarski outlined above.

As solution to this issue, I propose to add an extra condition to the determination the index of the incoming and outgoing scalar fields.  Instead of just taking the first match in the vertex's array of fields as the position of the field, I suggest first removing all positions that have nesting.

**Comment by wkotlarski** [comment]
I think I've already patched that (just not on the upstream). Can you check this commit
21d2d7e0201132ae2428544782ee67e68f801402

**Comment by dhjjacob** [comment]
Hi @wkotlarski, that seems to solve the issue.  Thank you for patching this.
