### ISSUE TITLE
disable decay calculation if not using loop library

### ISSUE THREAD

**Issue by wkotlarski** [FlexibleSUSY/FlexibleSUSY#166]
@Expander, @uukhas. I need to set a variable in `FlexibleSUSY.m` depending on whether a code was configured with or without dedicated loop library. Is that possible?

Here's some background: Decays require dedicated loop library. Whether decays are calculated or not is controlled by `FSCalculateDecays` variable in  `FlexibleSUSY.m`. Even if the user sets `FSCalculateDecays = True` I need to override it if we don't use LoopTools.

**Comment by Expander** [comment]
Out of my head I see the following option:

* The `configure` script copies the `FlexibleSUSY.m.in` file to the model directory. In this step, some tags are replaced, for example `@CLASSNAME@`.

* The function `update_model_makefiles()` modifies the model's `module.mk` file to replace/extend some functionality, based on the variables set in the `FlexibleSUSY.m.in` file.

These two points do something that is similar to what you desire. One could add a function to the `configure` script, which enables/disables the decays based on the chosen configuration. I.e. you may write in `FlexibleSUSY.m.in`
~~~
FSCalculateDecays = Automatic;
~~~
(or similar, e.g. `FSCalculateDecays = @FSCalculateDecays@`) and replace the r.h.s. by `True` or `False`, based on the chosen loop library.

**Comment by wkotlarski** [comment]
@Expander, sorry for a dumb question. But isn't `@CLASSNAME@` modified by `createmodel` script? That doesn't do the trick since at that point I don't know if I have `LoopTools` or not.

**Comment by Expander** [comment]
Sorry, I was dumb. Of course `@CLASSNAME@` is replaced in `createmodel`.

What I actually wanted to say is, that in the `configure` script there is a mechanism to load the model-specific `FlexibleSUSY.m` file into a Mathematica session. I was naively thinking, that one could use this mechanism to modify the `FlexibleSUSY.m` file.

But wait, I've discussed a cleaner mechanism with @uukhas here: https://github.com/FlexibleSUSY/FlexibleSUSY/pull/148

Cite:

Do you need the information about the chosen loop libraries? If so, I think a cleaner way would be to define
~~~
FSLoopLibraries = { FSSOFTSUSY };
~~~
at the top of `meta/FlexibleSUSY.m`.

In a second step, I'd propose that the configure script appends the following line to the `models/<model>/FlexibleSUSY.m` file, which contains the information about the configured loop libraries:
~~~
FSLoopLibraries = { FSSOFTSUSY, FSCOLLIER, FSFFLite, FSLoopTools };
~~~
When the `models/<model>/FlexibleSUSY.m` file is loaded, it overwrites the default choice `FSSOFTSUSY` from above. In `meta/Observables.m` you can then simply check which symbols are within `FSLoopLibraries` and enable/disable observables.

**Comment by wkotlarski** [comment]
Is `models/<model>/FlexibleSUSY.m` file created during `createmodel`. If yes, what happens when you do 2 `configure` with different options?

**Comment by Expander** [comment]
Yes, `models/<model>/FlexibleSUSY.m` is created by `createmodel`.

With my proposal (appending a line to `models/<model>/FlexibleSUSY.m`) there would be no inconsistency when `configure` is called multiple times with different options. This is because appending the line overwrites the setting of the previous one:
~~~
(* first configure created this line: *)
FSLoopLibraries = { FSSOFTSUSY, FSCOLLIER, FSFFLite, FSLoopTools };
(* second configure created this line: *)
FSLoopLibraries = { FSSOFTSUSY, FSLoopTools };
~~~

The reason why this works is the order in which we require the user to call the commands:
~~~
[1] ./createmodel
[2] ./configure
[3] make
~~~
Each of these commands can be called multiple times, without introducing an inconsistency. However, the order of the commands must not be changed, otherwise there may be a problem.

**Comment by wkotlarski** [comment]
For me that would solve all problems then. Is anyone working on it?

**Comment by Expander** [comment]
I'm currently not working on this.

Also, it appears to me that this approach should be extended to also add a line indicating whether FA/FC are available, for example as:
~~~
FSFeynArtsAvailable = True; (* or False *)
FSFormCalcAvailable = True; (* or False *)
~~~
This would avoid an ugly hack in PR #148 from @uukhas ;)

**Comment by uukhas** [comment]
@Expander, then I have question. There are two ways how to deal with `FA+CF`:
1) One can modify the `FSObservables` by adding `FToFConversionInNucleus` if `FSFeynArtsAvailable === True` and `FSFormCalcAvailable === True`. But then one has to change the way `meta/Observables.m` is loaded, because currently it is loaded before any variable of mentioned before takes an effect. So one can just remove `Observables.m` from `Needs` to some later place and make then "lazy" load of this package.

2) One can modify the function `IsObservable` by adding `FToFConversionInNucleus` to `FSObservables` in case `FSFeynArtsAvailable` and `FSFormCalcAvailable` are both `True`. 

In both cases I would also suggest to add `Locked` and `Protected` `Attributes` to these variables to avoid any possibility to modify them by case during evaluation of the code.

Also, the first option seems better for me, because we modify `FSObservables` only once, and in the second case we have to check all required variables all times this `IsObservable` function is called.

Once the decision is done I can implement all required things into `configure` and make `Observables.m` elegant again.

**Comment by Expander** [comment]
Hi @uukhas ,

I like your will to make `Observables.m` elegant again! Great word joke! :D

TBH, it is not clear to me which approach is better ATM. You are right, modifying `FSObservables` only once is a great benefit. Do you think this would work smoothly? I'm asking, because `Observables.m` requires/loads other modules as well and it is not clear to me ATM in which way they are affected in case they get reloaded.

To better judge the situation, could you please post a link to the version of `Observables.m` (repository and branch) that you are referring to and where we could look at?

The approach 2. would maybe require some kind of `FSInitObservables[]` function (or similar) to be called before calculating the observables. This function could remove observables that cannot be calculated due to missing FA/FC. It seems such an approach is not terribly messy, too.

**Comment by uukhas** [comment]
> Do you think this would work smoothly? I'm asking, because `Observables.m` requires/loads other modules as well and it is not clear to me ATM in which way they are affected in case they get reloaded.

Yes, it will work OK, because `Mathematica` does **not** reload modules, which are already loaded. Everything else is loaded before in `meta/FlexibleSUSY.m`, so all dependencies should be fine.

I already did this "lasy" `Needs` in the `meta/FlexibleSUSY.m` for ``NPointFunctions` `` and ``WilsonCoefficiens` `` packages (lines `3722-3733`) in #148 and it works fine.

I will write a code with these changes then and link the pull request to this issue.

**Comment by uukhas** [comment]
> To better judge the situation, could you please post a link to the version of `Observables.m` (repository and branch) that you are referring to and where we could look at?

This information, actually should not be mentioned in this issue, but as an answer to a quoted question I would like to note that this is done with 20cf298.

**Comment by wkotlarski** [comment]
Could you also tell me how to secure tests? I have to compile and run `FlexibleDecay` tests **only if** FS was compiled with extra loop libraries. I could use `$ENABLE_LOOPTOOLS` variable but this is not very generic.  Is there an idea how this should be handled?

**Comment by uukhas** [comment]
@wkotlarski, it seems that you need some additional variable `$EXTRA_LOOP_LIBRARY` and then, depending on the selection criteria on configured libraries (whether they can be called extra ones or no), you can secure test with it, right?

Why not just to check all required `$ENABLE_`s directly it tests?

**Comment by wkotlarski** [comment]
Sorry, now that I think about it, there's more to it than that. Since I've introduced a variable `FSCalculateDecays` I need to have access to it's values in tests. Because I might configure SM with loop libraries without decays. Then I shouldn't run `test_SM_FlexibleDecay` at all.

**Comment by uukhas** [comment]
@wkotlarski, do you setup `FSCalculateDecays` via `configure`? 

If yes, then you might like to add something like `CALCULATE_DECAYS := @CALCULATE_DECAYS@` in the beginning of `config/Makefile.in` and modify then `configure`'s function `replace_markers()` to replace `@CALCULATE_DECAYS@` with `yes` or `no`.

**Comment by wkotlarski** [comment]
No. `FSCalculateDecays` is read from `FlexibleSUSY.m.in`.

**Comment by Expander** [comment]
Hmm, can you read the `FlexibleSUSY.m` file from the model under consideration? Would that help?

**Comment by wkotlarski** [comment]
I will show you my solution later but in short I've created a file `test/FlexibleDecay.mk.in` where i set `ENABLE_FLEXIBLEDECAY := yes` and then include it in `test/module.mk` and control tests though `ENABLE_FLEXIBLEDECAY` variable.

**Comment by wkotlarski** [comment]
Can we close it? From my point of view everything now works.

**Comment by pathron** [comment]
This is the fix we have using for a good while now right? I guess this was just left open by mistake?
