### ISSUE TITLE
cannot enable observables in BLSM

### ISSUE THREAD

**Issue by wkotlarski** [FlexibleSUSY/FlexibleSUSY#178]
`BLSM` generates non zero `Ah`, `hh`, `VP` vertex of value
```
const std::complex<double> result = std::complex<double>(0,0.1)*((3.872983346207417*g1*Cos(ThetaW) - 5*g2*Sin(ThetaW))*ZA(gt1,0)*ZH(gt2,0) + 20*g1p1*Cos(ThetaW)*ZA(gt1,1)*ZH(gt2,1));
```
This breaks `g-2` calculation where we assume that in a triangle with photon emitted from scalar in the loop the scalar does not change its type.

**Comment by Expander** [comment]
I'm not an expert on the `BLSM`, sorry. In which way does it "break" the (g-2) calculation? Do you mean that the (g-2) result does contain genuine SM contributions, which must not be there in our BSM result?

**Comment by wkotlarski** [comment]
The assumption in the code is that massless gauge boson couple diagonally. Also, superficially, we just have a coupling of photon to uncharged particles `hh` and `Ah`. I would hope that numerically this coupling vanishes.

**Comment by Expander** [comment]
Do I understand correctly, that the implicit assumption can only be checked numerically and not at the meta code level?

**Comment by wkotlarski** [comment]
This now works correctly.

**Comment by dhjjacob** [comment]
@wkotlarski this error seems to have resurfaced.  I have been trying to get this model up and running for creating a test for g-2, and I seem to get an error when I make this model with g-2 enabled:

`models/BLSM/BLSM_FFV_form_factors.cpp: In instantiation of ‘static std::valarray<std::complex<double> > {anonymous}::FFV_SSF<Fj, Fi, V, S1, S2, F>::value(const typename flexiblesusy::BLSM_cxx_diagrams::field_indices<Field>::type&, const typename flexiblesusy::BLSM_cxx_diagrams::field_indices<Fi>::type&, const flexiblesusy::BLSM_cxx_diagrams::context_base&, bool) [with Fj = flexiblesusy::BLSM_cxx_diagrams::fields::Fe; Fi = flexiblesusy::BLSM_cxx_diagrams::fields::Fe; V = flexiblesusy::BLSM_cxx_diagrams::fields::VP; S1 = flexiblesusy::BLSM_cxx_diagrams::fields::hh; S2 = flexiblesusy::BLSM_cxx_diagrams::fields::Ah; F = flexiblesusy::BLSM_cxx_diagrams::fields::Fe; typename flexiblesusy::BLSM_cxx_diagrams::field_indices<Field>::type = std::array<int, 1>; typename flexiblesusy::BLSM_cxx_diagrams::field_indices<Fi>::type = std::array<int, 1>]’:
models/BLSM/BLSM_FFV_form_factors.cpp:203:71:   required from here
models/BLSM/BLSM_FFV_form_factors.cpp:3301:4: error: static assertion failed: Internal scalars in the FFV_SSF instantiation must be of the same type.
    static_assert(
    ^~~~~~~~~~~~~
Building models/BLSM/BLSM_a_muon.o
models/BLSM/BLSM_FFV_form_factors.cpp: In instantiation of ‘static std::valarray<std::complex<double> > {anonymous}::FFV_SSF<Fj, Fi, V, S1, S2, F>::value(const typename flexiblesusy::BLSM_cxx_diagrams::field_indices<Field>::type&, const typename flexiblesusy::BLSM_cxx_diagrams::field_indices<Fi>::type&, const flexiblesusy::BLSM_cxx_diagrams::context_base&, bool) [with Fj = flexiblesusy::BLSM_cxx_diagrams::fields::Fe; Fi = flexiblesusy::BLSM_cxx_diagrams::fields::Fe; V = flexiblesusy::BLSM_cxx_diagrams::fields::VP; S1 = flexiblesusy::BLSM_cxx_diagrams::fields::Ah; S2 = flexiblesusy::BLSM_cxx_diagrams::fields::hh; F = flexiblesusy::BLSM_cxx_diagrams::fields::Fe; typename flexiblesusy::BLSM_cxx_diagrams::field_indices<Field>::type = std::array<int, 1>; typename flexiblesusy::BLSM_cxx_diagrams::field_indices<Fi>::type = std::array<int, 1>]’:
models/BLSM/BLSM_FFV_form_factors.cpp:211:71:   required from here
models/BLSM/BLSM_FFV_form_factors.cpp:3301:4: error: static assertion failed: Internal scalars in the FFV_SSF instantiation must be of the same type.`

This is because FlexibleSUSY in this model can form an `SSF` diagram with a hh-Ah-Fe loop, where the hh and Ah scalars couple to the photon VP, and the fermion Fe mediates.  This problem eventuates whether or not there are vector diagrams, however if we go to the branch in https://github.com/FlexibleSUSY/FlexibleSUSY/pull/216 then there are `SVF` and `VSF` diagrams which have a VZ-hh-VP or VZp-hh-VP vertex.  

Is there a way to circumvent these diagrams being included in the model .cpp code?  Thanks.

**Comment by wkotlarski** [comment]
Why did it vanish in the first place?

**Comment by dhjjacob** [comment]
Not sure.  This error only appears if the FlexibleSUSY`LowEnergy block for muon g-2 is used in the FlexibleSUSY file.  The step where the couplingsThis model seems to have a lot of 'unexpected' diagrams for muon g-2, such as an FFV using Fv-Fv-VWm, with the neutrinos coupling to the external photon VP.  

Perhaps this issue could be rectified, at least for this model, by enforcing that the fields which couple to the photon must be charged using IsElectricallyCharged[] in the FFVFormFactors.m meta file?

**Comment by Expander** [comment]
If I understand correctly, one issue is that the neutrinos in this model mix with other BSM particles, so they are not purely SM-like. So, such diagrams seem plausible when looking only from this perspective.

What does `IsElectricallyCharged[]` yield for the `Fv` particles?

**Comment by wkotlarski** [comment]
I'm not sure @Expander. As Douglas wrote 
> the hh and Ah scalars couple to the photon VP

There are models where some coupling which make no sense are not 0 analytically but 0 numerically.

**Comment by dhjjacob** [comment]
> What does IsElectricallyCharged[] yield for the Fv particles?

False, same for hh, Ah, VZ, and VZp.

**Comment by Expander** [comment]
Would the issue be properly fixed, if one would add
~~~
ElectricCharge -> 0,
~~~
to `SARAH/Models/B-L-SM/particles.m` in line 82, i.e. for `Fv`?

**Comment by dhjjacob** [comment]
> Would the issue be properly fixed, if one would add
>
> ElectricCharge -> 0,
>
> to SARAH/Models/B-L-SM/particles.m in line 82, i.e. for Fv?

No, I tried this already for hh and Ah, to no effect.

**Comment by Expander** [comment]
Ok, I see. But just to get this physically right in my head: If the charge of these particles would be zero, then these diagrams should not be taken into account. So, then the issue seems to be that the information about the electric charge being zero is not correctly taken into account when selecting the diagrams. So, a fix could start there, right?

**Comment by dhjjacob** [comment]
Yes I agree.  I suggest changing the code in the IsDiagramSupported[] function from this for the SSF diagram:

      If[TreeMasses IsFermion[exchangeParticle] && TreeMasses IsScalar[photonEmitter] && TreeMasses IsScalar[photonEmitterAfter], 
         Return[True]
      ];

to something like this:

    If[TreeMasses IsElectricallyCharged[photonEmitter] && TreeMasses IsElectricallyCharged[photonEmitterAfter],
      If[TreeMasses IsFermion[exchangeParticle] && TreeMasses IsScalar[photonEmitter] &&TreeMasses IsScalar[photonEmitterAfter],
         Return[True]
      ],
      Return[False]
    ];

and similarly for the other diagrams.  What do you think?

**Comment by wkotlarski** [comment]
Are we ever going to need the fermion-fermion-gluon amplitude? Because if yes than this might be a problem.

**Comment by Expander** [comment]
> Are we ever going to need the fermion-fermion-gluon amplitude? Because if yes than this might be a problem.

In principle yes, for example we may at one point calculate the chromomagnetic dipole moment or similar.
But this is not the case for the `EDM.m` module, because there we deal only with the "electromagnetic dipole moment" (EDM). :)

For the chromomagnetic moment it could be that we need introduce a slightly different selection mechanism for the diagrams.
In this case we could rename the function to make clear that we're requiring an electrically/color charged particle.

So, I'd vote for trying @dhjjacob 's idea. We may do it in a separate branch to see if it in some way affects the tests that we have for g-2 for the properly working models.

**Comment by wkotlarski** [comment]
The problem is that all those observables: g-2, mu -> e gamma, b -> s gamma use the FFV code. Ideally, any future observable would do the same.

**Comment by Expander** [comment]
Hmm, then we may introduce a way to pose additional constraints on the coupling.
What about extending the function signature to take a predicate function that can be applied as an additional selection mechanism?
~~~.mathematica
IsDiagramSupported[graph_, diagram_, VectorEmitterPredicate_:True&] :=
   ...
~~~
It could then be called like this (if necessary):
~~~.mathematica
IsDiagramSupported[graph, diagram, TreeMasses`IsElectricallyCharged]
~~~

**Comment by dhjjacob** [comment]
My concern is that the `IsDiagramSupported[]` function is called from `FFVContributingDiagrams`, which, as @wkotlarski said, is used to be used ideally for any future F->FV observable.  Alternatively we could create a function to use instead of `IsElectricallyCharged[]`:

`IsCorrectlyCharged[field,vector]:=`

which would check if the input `field` has the charge of input `vector`.  For example `IsCorrectlyCharged[field,VP]` would output identical results to `IsElectricallyCharged[]`, and `IsCorrectlyCharged[Fu,VG]` and `IsCorrectlyCharged[Fv,VG]` would return True and False respectively.

**Comment by Expander** [comment]
Good idea! Would you mind trying this approach to see if the issue can be fixed in this way?

Although I'd recommend to rename the function as `IsChargedUnder[field,vector]` or similar.
(One should probably also use the generic names ``TreeMasses`GetPhoton[]`` etc.)

**Comment by dhjjacob** [comment]
Hi @Expander, okay I will start a branch for this and get going.

**Comment by Expander** [comment]
Thanks in advance!

**Comment by dhjjacob** [comment]
Hi @Expander  @wkotlarski, you can now see the branch in the pull request: https://github.com/FlexibleSUSY/FlexibleSUSY/pull/340.  Thanks.

**Comment by wkotlarski** [comment]
close by #340
