### ISSUE TITLE
new test matrix

### ISSUE THREAD

**Issue by wkotlarski** [FlexibleSUSY/FlexibleSUSY#198]
@Expander, @uukhas, I've extended the test matrix to include collier. If I configure FS with Collier, will it calculate everything with collier? What's the precedence of libraries. If there's collier, will it will be always used everywhere? Similarly, if there's only LoopTools will it be used everywhere? If yes then it makes sense to configure FS 3 times, separately: 
- without collier or LT
- with LT but without collier
- with collier.but without LT

**Comment by uukhas** [comment]
Default loop library is `softsusy`. It can always be enabled by `Loop_library::set(0)`. If one forgets to call explicitly `::set(0)` before first `::get()`, then the program will print the warning and turn on `softsusy`.

If one setups with `looptools`, then one can use `softsusy` and `looptools` at runtime. To use `looptools` one has to call `Loop_library::set(2)` (you can put negative number, then program will just tell you all configured libraries and their respective numbers).

You can add `collier` and `fflite` as well. But `fflite` can be enabled only with `softsusy`, because then `threads` can be used.

**Comment by uukhas** [comment]
If one enables the library by the call of `::set(<...>)`, then everything is calculated with this library only.

**Comment by wkotlarski** [comment]
Tests don't take any input. So one cannot switch libraries within tests. One can only hardcode the library choice in them. Should we have different versions of tests for different libraries?

**Comment by uukhas** [comment]
Maybe one can write some `.sh` master test, which will be launching some specific tests with different input for them (if it's possible to give some input to them)?

**Comment by Expander** [comment]
There is a test which cross-checks all configured loop libraries. But I guess this is not what you're thinking of, @wkotlarski , right?

Having `.sh` test that cross-check specific models with different loop libraries would be an option.

I see another option: We could introduce another flag value `-1` with the following behavior:
* If the environment variable `FLEXIBLESUSY_LOOP_LIBRARY` is set to some value, use this loop library
* Otherwise use softsusy (this is the current behaviour).
We may then change the test SLHA input files to have `FlexibleSUSY[31] = -1`. One can then control the used loop library from the test suits by setting `FLEXIBLESUSY_LOOP_LIBRARY` accordingly.

**Comment by wkotlarski** [comment]
I'd like the `FLEXIBLESUSY_LOOP_LIBRARY` option. I do not want to hardcore loop library in the tests.

**Comment by Expander** [comment]
Yes, hardcoring is not so nice. ;D

@uukhas since you are the master of loop libraries, would you mind preparing a PR?

**Comment by uukhas** [comment]
Just one question. 

By environment variable you mean usage of `<cstdlib>`s function `std::getenv()`, right?

**Comment by Expander** [comment]
> Just one question.
> 
> By environment variable you mean usage of `<cstdlib>`s function `std::getenv()`, right?

Yes, that what I was thinking about
