### ISSUE TITLE
Leptoquarks probably break the calculation of a lot of observables (e.g g-2)

### ISSUE THREAD

**Issue by wkotlarski** [FlexibleSUSY/FlexibleSUSY#24]
Routine that calculates the g-2 written by Jobst use vertices in `MODELNAME_cxx_diagrams.hpp`. There the color structures are stripped away. If you have a model with a leptoquark you will have a contributions to various electroweak observables from closed loops with color charged particles. 
So the result for those diagrams will be off by some color Casimir.

Kien is now working on a version of vertex routines with color structures which will solve this problem. He should be done soon.

SARAH does contain a model called ScalarLeptoquarks, which is based on refs. 1511.01900 and 1512.06828. If you look into 1511.01900, then they consider a leptoquark contributions to g-2. This might be a good testing ground for the new routines.

**Comment by Expander** [comment]
Many thanks for reporting this issue and for looking into a potential solution!

The `Vertices` module was originally intended to generate the vertices needed to calculate the SARAH-generated self energies and tadpoles.  These self energies / tadpoles are written in the form

    C * V1 * V2 * LoopFunction

where `V1` and `V2` are vertex expressions generated by the `Vertices` module and `C` is a color factor. Due to this SARAH-generated structure, the color factor is stripped off from the vertices. It is clear that this can lead to problems when these vertices are used in other contexts.

I'm wondering if it makes sense to introduce a color factor in `g-2` as well?  Then one may be able to use the existing vertices.  However, one would have to determine the color factor, of course.

**Comment by wkotlarski** [comment]
I think now everything works.
