### ISSUE TITLE
default munuSSM parameter point

### ISSUE THREAD

**Issue by wkotlarski** [FlexibleSUSY/FlexibleSUSY#303]
@pathron asked in which models decays are not enabled by default. One tricky point is that there are some models which have default parameter points which break decays. This then would break tests. An example is the munuSSM
```
     36     1.95525343E+00   # Ah(2)
1000017     4.19539888E+01   # Ah(3)
1000018     5.41940999E+02   # Ah(4)
1000019     5.43184936E+02   # Ah(5)
2000018     6.60319708E+02   # Ah(6)
```
You can see there's a ~2 GeV pseudoscalar. This casses problem when we try to determine the number of active quark flavour. And accepted answers are only 5 or 6. Could we maybe change the default point? Was there any though given to that point?

**Comment by pathron** [comment]
I have no problem with the example point being changed (it is just an example, not a default — default implies that somehow it can be useful just to stick to this choice).  

A bigger issue, that will apply also to to other models is what happens when this point is found in a scan ?  How do we handle this?

**Comment by Expander** [comment]
Yes, we're free to change it, as long as the parameter point works. :)
