### ISSUE TITLE
Improve performance of one_loop_decay_diagrams

### ISSUE THREAD

**Issue by wkotlarski** [FlexibleSUSY/FlexibleSUSY#328]
Instead of
```cpp
auto c1 = lib.C1(a,b,c,d,e,f);
auto c2 = lib.C2(a,b,c,d,e,f);
```
do
```cpp
const std::array<std::complex<double>, 7> coeffs;
lib.C(coeffs, a, b, c, d, e, f); // fills coeffs with C0, C1, C2, C00, C11, C12, C22
const auto c1 = coeffs.at(1);
const auto c2 = coeffs.at(2);
```

**Comment by Expander** [comment]
Very cool idea! Thanks to @uukhas for designing the interface such that this is so easily possible! :)

**Comment by wkotlarski** [comment]
I think the speedup is hardly impressive. If there's anything, we're talking around 5%.

**Comment by Expander** [comment]
I think this also depends on the library that is used: If the library calls all functions in one efficient go, then this may be beneficial.

**Comment by wkotlarski** [comment]
[This](https://github.com/FlexibleSUSY/FlexibleSUSY/tree/speedup-decay-1L-amplitudes) contains the implementation of the above idea. Sadly, I don't see any measurable difference. What should we do? Should we change it or leave it? Maybe @uukhas has some comments.

**Comment by uukhas** [comment]
I am not sure about the speed up of these different approaches. The Idea of that interface was just the ability to change the loop library after the compilation of ``C++`` code and not to increase the speed of the calculation.

Well, for ``COLLIER`` library the usage of the unified call (aka *new* one in this PR) makes a difference, because there all coefficients are calculated in the same time and not cashed in a simple way (I think, that I failed to make a cache there work in a desired way).

For the ``LoopTools`` it seems that there is no difference at all, because of some magical internal cache.

For ``softsusy`` and ``fflite`` the difference is only in the amount of function calls. The *new* interface reduces the amount of them.

Anyways, I think that moving the responsibility for a speedup to libraries themselves is an improvement, so the *new* way of calling them is better.

**Comment by uukhas** [comment]
**P.P.S.** Also, in ``C++`` code there is a possibility to use (see ``loop_library_interface.hpp``):
```C++
looplibrary::Acoeff_t
looplibrary::Bcoeff_t
looplibrary::Ccoeff_t
looplibrary::Dcoeff_t
```
instead of 
```C++
std::array<std::complex<double>, 1>
std::array<std::complex<double>, 3>
std::array<std::complex<double>, 7>
std::array<std::complex<double>, 11>
```

**Comment by wkotlarski** [comment]
I've implemented Vova's suggestion regarding types. So if you believe that this way of calling functions is better than I'll make this change after we release the code (version 2.6.1 or something).
