### ISSUE TITLE
MODEL_SPECIFIC_MODULES sometimes is not updated

### ISSUE THREAD

**Issue by uukhas** [FlexibleSUSY/FlexibleSUSY#370]
Sometimes I need to completely reload ``FlexibleSUSY`` and compile it (if I want to check someone's repository).
And usually for the model under interest I specify some additional subset of observables in ``FlexibleSUSY.m`` file.
So that I copy it to a new repository right before ``configure`` stage.

This set of operations **does not** update ``@MODEL_SPECIFIC_MODULES@`` in ``models/$MODEL/module.mk``,
which leads to a failure during compilation.

How to reproduce:
```
MODEL="SM"
vim models/$MODEL/FlexibleSUSY.m                 # Change something inside
cp models/$MODEL/FlexibleSUSY.m ~                # Copy new settings with some important data 
cd ..                                
rm -rf FlexibleSUSY/                             # Remove directory because of recent merge, for example
git clone <any repo> 
cd FlexibleSUSY/
./createmodel --name=$MODEL
mv ~/FlexibleSUSY.m models/$MODEL/FlexibleSUSY.m # Restore our important settings
./configure --with-models=$MODEL                 # Does not update @MODEL_SPECIFIC_MODULES@
```

**Comment by Expander** [comment]
If I understand correctly, the issue is the following:

* The command `./createmodel --name=$MODEL` creates `$MODEL/module.mk` and `$MODEL/FlexibleSUSY.m`.
* Afterwards, the command `mv ~/FlexibleSUSY.m models/$MODEL/FlexibleSUSY.m` overwrites the file `models/$MODEL/FlexibleSUSY.m`. The new file `models/$MODEL/FlexibleSUSY.m` will have a time stamp that is newer than the overwritten one and that is also newer than `$MODEL/module.mk`. (This is at least what is happening on my machine. If this is not the case, then this will be the origin of the issue.)

I now suspect that in `configure` the offending part is around the line:
~~~.bash
{ find "$mkfile" -newer "$model_file" | grep ^; } > /dev/null 2>&1 && return
~~~
where `$mkfile == $MODEL/module.mk` and `$model_file == models/$MODEL/FlexibleSUSY.m`. The `find` command returns `$mkdifle`, if it is newer than the `$model_file`. This will not be the case for the above setup. I.e. the `find` command will not print any output. Then, `grep ^` searches for some output, but will not find any. Thus, the command inside `{ ... }` will fail. As a result, `return` is not called and the `$mkfile` should be updated.

So, I don't understand what is going on. I will now try to reproduce your approach step-by-step.

**Comment by uukhas** [comment]
I also think that the problem is connected with timestamps. Unfortunately, that time I had no instruments to check it explicitly. 
My attempt will also be now to look close to the line, which you have mentioned. 

Is there some build-in linux command to check timestamps as well?

**Comment by uukhas** [comment]
I noticed, that the problem appears only for **mv** command. For **cp** the `@MODEL_SPECIFIC_MODULES@` is updated correctly.

**Comment by uukhas** [comment]
For **cp**, if one uses `stat`, then:
```
Access(module.mk) == Modify(module.mk) == Change(module.mk)
==
Access(FlexibleSUSY.m) < Modify(FlexibleSUSY.m) == Change(FlexibleSUSY.m)
```
For **mv**:
```
Modify(FlexibleSUSY.m) 
<
Access(module.mk) == Modify(module.mk) == Change(module.mk)
<
Access(FlexibleSUSY.m) < Change(FlexibleSUSY.m)
```

**Comment by Expander** [comment]
Ah, that may be the origin of the issue that you see! `mv` does not modify the time stamp, right?

**Comment by uukhas** [comment]
It seems so. Which timestamp `-newer` actually checks?

**Comment by Expander** [comment]
According to https://man7.org/linux/man-pages/man1/find.1.html `-newer` checks the last modification time:
~~~
       -newer reference
              Time of the last data modification of the current file is
              more recent than that of the last data modification of the
              reference file.  If reference is a symbolic link and the
              -H option or the -L option is in effect, then the time of
              the last data modification of the file it points to is
              always used.
~~~

**Comment by uukhas** [comment]
Thank you, @Expander, I have some large problems in finding these descriptions :(
What would be the best strategy to cure this problem?

**Comment by Expander** [comment]
It seems to me that we have the following options:
* We don't test for the modification time and always update the `module.mk` file. This has the drawback, that the we may often do unnecessary work that substantially increases the time to run `./configure`.
* Don't use `mv` in your setup, instead use `cp`. :)

Personally, I'd vote for the latter option, because I find it annoying when `./configure` takes a lot of time, because I run it quite frequently. Or we may search for a way to speed-up the update process for `module.mk`.

**Comment by uukhas** [comment]
Is this step slow, because we execute `mma_symbol_is` many times? 
If yes, then we can speed up the `get_model_specific_corrections` by the following:
* `SM` is always required, hence we can remove
   ```
    mma_symbol_is "$model_file" "$math_cmd" "UseHiggs2LoopSM" "True"    && ho="${ho} SM"
    mma_symbol_is "$model_file" "$math_cmd" "UseHiggs3LoopSM" "True"    && ho="${ho} SM"
    mma_symbol_is "$model_file" "$math_cmd" "UseHiggs4LoopSM" "True"    && ho="${ho} SM"
    mma_symbol_is "$model_file" "$math_cmd" "UseSMAlphaS3Loop" "True"   && ho="${ho} SM"
    mma_symbol_is "$model_file" "$math_cmd" "UseSMAlphaS4Loop" "True"   && ho="${ho} SM"
    mma_symbol_is "$model_file" "$math_cmd" "FlexibleEFTHiggs" "True"   && ho="${ho} SM"
   ``` 
* For other checks we can first use a single `grep` for all mathematica symbols (like `UseHiggs2LoopMSSM`) in order
   to get only those, which are present in `FlexibleSUSY.m` and then run `mma_symbol_is` only for them.

**Comment by Expander** [comment]
> Is this step slow, because we execute `mma_symbol_is` many times?

Yes, this is the reason. Starting the `math` kernel takes time, and this is done multiple times.

Fusing multiple calls may be an option. Using `grep` may not always work, because the user may not always write simple expressions such as `UseHiggs2LoopSM = True`, but more complicated expression on the r.h.s.

**Comment by uukhas** [comment]
* I meant the following: calling `grep` just in order to find, whether user use the variable like `UseHiggs2LoopSM` **at all**. If yes, then there is a reason to run `mma_symbol_is` for this variable. If it is missing, then there is no sense.
And once we know, which words from the set `UseSMYukawa2Loop, UseHiggs2LoopMSSM, UseHiggs3LoopMSSM, UseMSSMAlphaS2Loop, UseMSSMYukawa2Loop, UseHiggs2LoopNMSSM, UseHiggs3LoopSplit` are used, we can launch `mma_symbol_is` for every one from them.
* Or we can just fuse all tests into one here-file, as you said.

**Comment by uukhas** [comment]
I suggest to speed up `get_model_specific_corrections` in a separate PR.

**Comment by uukhas** [comment]
Done in #383-#384.
