### ISSUE TITLE
don't create new symbol in Himalaya.m

### ISSUE THREAD

**Issue by wkotlarski** [FlexibleSUSY/FlexibleSUSY#374]
In `FlexibleSUSY.m` `g3` exists as ```Himalaya`g3```. Can we replace it in `Himalaya.m` with ```SARAH`g3``` as is done with `g1`?

**Comment by Expander** [comment]
Thanks for finding this! I think this is due to the order of the package imports in `FlexibleSUSY.m`. Please feel free to replace it. (I think there is a test to ensure that spectrum generators using Himalaya still work, right?)

Btw, I strongly believe this issue (and many similar issues, involving `shdw` warnings etc.) have their origin in a design flaw in Mathematica's "package system". For some time I was looking to avoid such issues and improve how we import sub-packages in FS, but non of them is optimal. If you have some good ideas how to avoid these context bugs, I'd be very happy to discuss and include them!

**Comment by Expander** [comment]
I think this issue is no longer present. In particular in `Himalaya.m` we have:
~~~.m
{ RenormalizationScheme, Lambda3L, Lambda3LUncertainty,
  \[Mu], SARAH`g1, Susyno`LieGroups`g2, SARAH`g3, SARAH`vd, SARAH`vu,
  MSQ2, MSD2, MSU2, MSL2, MSE2,
  Au, Ad, Ae, Yu, Yd, Ye, M1, M2, M3, mA };
~~~
Here ``SARAH`g3`` is referenced, i.e. no new symbol `g3` is introduced.

Furthermore, running
~~~.m
AppendTo[$Path, FileNameJoin[{Directory[], "meta"}]];

Needs["SARAH`"];
Needs["FlexibleSUSY`", FileNameJoin[{Directory[], "meta", "FlexibleSUSY.m"}]];

workingDirectory = Directory[];
SARAH`SARAH[OutputDirectory] = FileNameJoin[{workingDirectory, "Output"}];
SARAH`SARAH[InputDirectories] = {
    FileNameJoin[{workingDirectory, "sarah"}],
    ToFileName[{$sarahDir, "Models"}]
};

Print["Current working directory: ", workingDirectory];
Print["SARAH output directory: ", SARAH`SARAH[OutputDirectory]];
Print["Starting model: ", ToString[HoldForm[Start["MSSMNoFV"]]]];

Start["MSSMNoFV"];

MakeFlexibleSUSY[InputFile -> FileNameJoin[{"models/NUHMSSMNoFVHimalaya","FlexibleSUSY.m"}],
                 OutputDirectory -> "models/NUHMSSMNoFVHimalaya",
                 DebugOutput -> False];

In[12]:= ?g3                                                                                                                                                                                              

Out[12]= SARAH`g3
~~~
shows that the symbol `g3` is defined only once (as ``SARAH`g3``).

I propose to close this issue. (Please re-open it when the issue re-appears.)
