### ISSUE TITLE
bared scalars and other things

### ISSUE THREAD

**Issue by uukhas** [FlexibleSUSY/FlexibleSUSY#379]
Inside `TreeMasses` I have found the following lines:
```wolfram
IsScalar[SARAH`bar[sym_]] := IsScalar[sym];
...
IsFermion[Susyno`LieGroups`conj[sym_]] := IsFermion[sym]; 
...
IsVector[SARAH`bar[sym_]] := IsVector[sym];
```
My **question is**: should we try to avoid these things?

Scalars and vectors in SARAH are wrapped only by `conj`, **iff** I am not mistaken. Hence the `bar` wrapper should mean some mistake.

Weil fermions can be wrapped by `conj`, but do we use 2-spinors somewhere on FlexibleSUSY level?

**Proposal**: to use ``Utils`AssertOrQuit`` for these cases.

**Comment by wkotlarski** [comment]
This is perfectly fine. You might want to know if `bar[Fe]` is a scalar or not. And then
```wolfram
IsScalar[SARAH`bar[sym_]] := IsScalar[sym];
```

**Comment by uukhas** [comment]
I do not know, how often we use them, maybe not a lot. 
The small (maybe negligible) speed boost might be if we use:
```wolfram
IsScalar[_SARAH`bar] = False;
IsVector[_SARAH`bar] = False;
```
Which should always be correct for sure. And:
```wolfram
IsFermion[_Susyno`LieGroups`conj] = False;
```
if we do not work with Weyl fermions.

**Comment by Expander** [comment]
Sorry, but I'd be very careful here. Can we guarantee that `bar[]` is always wrapped around a fermion? I believe we cannot guarantee this, because we have no control over SARAH and the user's model file. The old code
~~~.wl
IsScalar[SARAH`bar[sym_]] := IsScalar[sym];
~~~
would correctly handle even strange cases such as `bar[scalar]`. The new proposal
~~~.wl
IsScalar[_SARAH`bar] = False;
~~~
would not do that. I.e. when we use the proposed new formulation, we'd add an implicit assumption that everything is always correctly formulated, which I find a bit dangerous. So, I'd propose to keep the current (more "secure") version.

**Comment by uukhas** [comment]
So, we follow GIGO, right?
Would it be somehow user-friendly to create some warning-wrapper as well, like in #271 or similar?

**Comment by Expander** [comment]
> So, we follow GIGO, right?

Yes, kind of. :)

> Would it be somehow user-friendly to create some warning-wrapper as well, like in #271 or similar?

Yes, I this might be a good alternative.
