### ISSUE TITLE
return of the old bug

### ISSUE THREAD

**Issue by wkotlarski** [FlexibleSUSY/FlexibleSUSY#39]
@ioloyz re-introduced in commit c9ecf50aaa210c374581af969bc3930dd30d3168 a bug fixed in commit 7da3f384db897d3138fd2f78c48fb15c478bc4da.

**Comment by Expander** [comment]
Oh.

In which generated file(s) did you spot this bug?  (I'd like to reproduce it.)

**Comment by wkotlarski** [comment]
The error will occur if you have a pseudoscalar - fermion - fermion coupling. Then the parameters needed to evaluate the vertex will not be defined in the vertex struct.

**Comment by iolojz** [comment]
Should we close this bug? @wkotlarski

**Comment by wkotlarski** [comment]
Does it work now? Do we have a unit test for this case?

**Comment by iolojz** [comment]
It probably does. No, we do not. Do you want to write one? ;)

**Comment by wkotlarski** [comment]
Yes. I can do it. But now I'm super busy. So please leave the bug open until I write the unit test.

**Comment by iolojz** [comment]
Alright, thank you :)

**Comment by iolojz** [comment]
If you still wish to write the unit test for this, it is probably very easy to do by having a look at `test/test_SM_cxxdiagrams.meta` and `test/test_SM_cxxdiagrams.cpp.in` from https://github.com/FlexibleSUSY/FlexibleSUSY/pull/62.

**Comment by iolojz** [comment]
Can this be closed now?

**Comment by wkotlarski** [comment]
@Expander, I've added a test that will catch this error in ` meta/CXXDiagrams.m`. There are many places where `CreateLocalConstRefs` is used though. And this test only checks the `CXXDiagrams.m`.

**Comment by Expander** [comment]
Thanks for adding this test! Although, I'm not sure I understand what the bug is.

When I have a vanishing sum (like `A + B = 0`) and I'm extracting local `const` refs from it, I'd have
~~~
const auto A = MODELPARAMETER(A);
const auto B = MODELPARAMETER(B);

const result = A + B;
~~~
wouldn't the `result` still be zero?

**Comment by wkotlarski** [comment]
In the past, we parsed the sum of left and right part of vertex in search of model parameters for which we have to create definitions in vertex. If left part = - right part, the sum is 0, and no definition is created.

**Comment by Expander** [comment]
Ok, I see, it's about the left- and right-chiral parts of a vertex.
Anyway, thanks for the explanation! :)

**Comment by Expander** [comment]
Do I understand correctly, that this bug is in principle still present, but does somehow not show up in the models we've studied so far? Or does the bug appear and can be reproduced?

Also, do I understand correctly, that the bug is not in the `CreateLocalConstRefs` function, but actually in the way this function is used within `CXXDiagrams.m`?

**Comment by wkotlarski** [comment]
I'd say so. `CreateLocalConstRefs` function is fine, it's how it's called in `CXXDiagrams` (and few other places). The bug is now fixed. It only appears in special cases. I forgot which model did exhibit it, I'm trying to find it out again.

**Comment by Expander** [comment]
Ok, I understand. Many thanks!
