### ISSUE TITLE
library handling JSON files

### ISSUE THREAD

**Issue by wkotlarski** [FlexibleSUSY/FlexibleSUSY#398]
@Expander, we are approaching the point when it would be good to have a robust way of writing JSON files. For now we did it in a not-so-fancy way like
```cpp
std::ofstream wc_json;    
wc_json.open ("WC_@ModelName@.json");    
wc_json << "{\n\"eft\": \"WET\",\n"; 
...
```
This is not scalable. In the past I have used [this](https://github.com/nlohmann/json) library to handle JSON. It's header only and released under the MIT license. Would it be ok to add it to `src`?

**Comment by Expander** [comment]
Good idea!

I'd also prefer a header-only library, because it is much easier to handle.

One note, though: So far, third-party libraries are included in FS in a directory in the root directory, for example `fflite` and `slhaea`. To be consistent, we could put the json library into a `json` directory as well.

One additional question/wish: In my experience it would be best if we would include the `json.hpp` file only in `.cpp` files in FS. I.e. we should avoid including it in header files. This would have the benefit that we don't suffer from substantially increasing the compile time.

**Comment by wkotlarski** [comment]
I've made a PR #399  which adds this header and uses it for outputting of `C7` and `C8` Wilson coefficients. If we ever need to heave json in a header we can also use a [nlohmann/json_fwd.hpp](https://github.com/nlohmann/json/blob/develop/include/nlohmann/json_fwd.hpp).

**Comment by uukhas** [comment]
@wkotlarski, should it be closed?
