### ISSUE TITLE
error after 'Converting self energies ...'

### ISSUE THREAD

**Issue by wkotlarski** [FlexibleSUSY/FlexibleSUSY#467]
This looks odd... It's a 5x5 lists. Seems ok to me... 
```
Error: could not convert list to matrix expression: 
{{Sqrt[2] vd Ye[1, 1], Sqrt[2] vd Ye[2, 1], Sqrt[2] vd Ye[3, 1], 
  Sqrt[2] g2 vL[1], -2 ϵ[1]}, 
 {Sqrt[2] vd Ye[1, 2], Sqrt[2] vd Ye[2, 2], Sqrt[2] vd Ye[3, 2], 
  Sqrt[2] g2 vL[2], -2 ϵ[2]}, 
 {Sqrt[2] vd Ye[1, 3], Sqrt[2] vd Ye[2, 3], Sqrt[2] vd Ye[3, 3], 
  Sqrt[2] g2 vL[3], -2 ϵ[3]}, {0, 0, 0, 2 MassWB, Sqrt[2] g2 vu}, 
 {-(Sqrt[2] sum[j1, 1, 3, vL[j1] Ye[1, j1]]), 
  -(Sqrt[2] sum[j1, 1, 3, vL[j1] Ye[2, j1]]), 
  -(Sqrt[2] sum[j1, 1, 3, vL[j1] Ye[3, j1]]), Sqrt[2] g2 vd, 2 μ}}
```

**Comment by Expander** [comment]
Where exactly does this error and expression occur? Which model did you use?

**Comment by wkotlarski** [comment]
After
```
Converting self energies ...
[..................................................] 37/37
Error: could not convert list to matrix expression:
...
```
This is a version of a model we got yesterday in a bug report. I'm not sure if I can share it so I've send it to you via email.

**Comment by Expander** [comment]
I think the issue is the following: For this model `SARAH` determines the analytic form of the 5x5 lepton mass matrix, let's call it $M_e$. This mass matrix seems to contain sub-matrices, like so (sketchy):
```
M_e = (Y_e   | vL    | e     )
      (0,0,0 | M2    | g_2v_u)
      (x,x,x |g_2v_d | 2mu   )
```
where $Y_e$ is the 3x3 lepton Yukawa coupling matrix.

Now, if one writes in the FlexibleSUSY model file:
~~~.m
LowScaleInput = {
   {Yu, Automatic},
   {Yd, Automatic},
   {Ye, Automatic}
}

InitialGuessAtLowScale = {
   {Yu, Automatic},
   {Yd, Automatic},
   {Ye, Automatic}
}
~~~
then FlexibleSUSY tries to analytically solve the relation between $M_e$ and $Y_e$ from above for $Y_e$. (`Automatic` means: Please try to fix $Y_e$ automatically in terms of the known SM fermion masses.) However, in the above case, where $M_e$ contains $Y_e$ as sub-matrix, FlexibleSUSY fails to do so.

Note: This analytic solution for $Y_e$ works only models where the relation is simple enough, like in the MSSM, where $M_e=Y_ev_d/\sqrt{2}$ $\Rightarrow$ $Y_e=\sqrt{2}M_e/v_d$.

A solution (or workaround) would be to set the values of $Y_e$ by hand in the model file, for example like so:
~~~.m
LowScaleInput = {
    {Ye[1,1], Sqrt[2] downLeptonsDRbar[1,1] / vd},
    {Ye[2,2], Sqrt[2] downLeptonsDRbar[2,2] / vd},
    {Ye[3,3], Sqrt[2] downLeptonsDRbar[3,3] / vd}
};
~~~
(Note that `vd` must be fixed as well, otherwise one would divide by zero.) The symbol `downLeptonsDRbar` stands for the diagonalized 3x3 down-lepton DR-bar (or MS-bar for non-SUSY models) mass matrix (see the FS-2.0 manual).

**Comment by wkotlarski** [comment]
I see... Just by the name, I thought that maybe `ToMatrixExpression` just creates a matrix. But it actually does something else. Ok. This makes sense. If the guy from yesterday get back in touch I'll point him to this. Thanks!
