### ISSUE TITLE
displayUpQuarkPoleMass etc

### ISSUE THREAD

**Issue by wkotlarski** [FlexibleSUSY/FlexibleSUSY#498]
`FlexibleDecay` in `src/decays/decay_functions.cpp` introduced `sm_down_quark_running_masses` function (and analogue one for up-type quarks). Could I get for uniformity a set of function similar to #479 but for quarks?

**Comment by Expander** [comment]
Excellent idea!

I think a function `displayUpQuarkPoleMass` does not make much sense for light quarks. Their "pole" masses should not be used in calculations anyway.

We should definitely introduce:
* `displayUpQuarkRunningMass` 
* `displayDownQuarkRunningMass`

**Comment by pathron** [comment]
Yes no pole masses or light quarks but otherwise good.  Can give the top quark pole mass.  I think we don't do bottom pole mass calculation ourselves though softsusy did?  This is something we could discuss and comes up in gambit because some codes, e.g. SUSYHIT give the user the option to supply their own bottom pole mass.
