### ISSUE TITLE
W-mass calculation in B-L-SM

### ISSUE THREAD

**Issue by dzsoga** [FlexibleSUSY/FlexibleSUSY#534]
Cannot build the BLSM model (provided in sarah)  with the option:
FSWeakMixingAngleInput = FSFermiConstant

Although it fulfills the criterion "the BSM model contains all SM particles and the BSM gauge group contains the SM gauge group as a factor"

**Comment by Expander** [comment]
Are you using FlexibleSUSY's `BLSM` model, where you have added the statement `FSWeakMixingAngleInput = FSFermiConstant`? Could you please paste the error message here?

**Comment by dzsoga** [comment]
Yes, I'm using the BLSM model files provided in the FlexibleSUSY directory `/model_files/BLSM`
During compilation it calls the BLSM model file in the model diractory of SARAH, right? 
I try to build a model provided in the installation guide:

1. I add the statement `FSWeakMixingAngleInput = FSFermiConstant` into the file  `/model_files/BLSM/FlexibleSUSY.m.in`
2. Then run `./createmodel --name=BLSM` and `./configure --with-models=BLSM`  these two are compiled without a problem. Then, when the command `make` is run it returns the error message, shown in the screenshot. 

![Képkivágás](https://user-images.githubusercontent.com/107123755/234232368-a9e01048-8305-43c1-b2af-3567ec16aade.PNG)

**Comment by wkotlarski** [comment]
Hi @dzsoga. Which version of FlexibleSUSY are you using? Version 2.7.1 works fine and I don't get this error.

**Comment by dzsoga** [comment]
I'm also using 2.7.1, fresh installation. :(

**Comment by dzsoga** [comment]
I'm using version 4.14.5 of SARAH.

**Comment by Expander** [comment]
I can reproduce this error with Wolfram Language 13.0.0 Engine, SARAH 4.15.1 on the `development` branch:
~~~
----------------------------------------------------------------------
Creating two-scale solver
----------------------------------------------------------------------
Creating class for convergence tester ...
Creating class for high-scale constraint ...
Error: Cannot use Fermi constant to determine weak mixing angle!
   Please use FSWeakMixingAngleInput = Automatic or FSMassW
Error: The code generation failed!
~~~

**Comment by Expander** [comment]
I ran the following to enable debug output from the meta code:
~~~
./createmodel --name=BLSM -f --enable-debug
./configure --with-models=BLSM
make
~~~
I get the following error from the `WeinbergAngle` module:
~~~
Debug<WeinbergAngle>: Error: DeltaVBwave does not work since there are not 3 neutrinos
~~~
It seems that the model has 6 neutrinos (not 3), because it has 3 generations right-handed neutrinos, which mix with the left-handed neutrinos, yielding (as far as I can see) 6 mixed Majorana neutrinos. (Please correct me if I'm wrong.)

The code in `WeinbergAngle` is not general enough to handle this case, sorry. :( Basically, the 3 SM-like neutrinos cannot be easily distinguished from the non-SM neutrinos, due to the mixing. In other words, the model does not contain the 3 pure SM neutrinos, i.e. does not really match the requirements. (Probably the statement about the requirements is not clearly enough expressed.)

One workaround would be to not mix the left-handed and right-handed neutrinos. But I'm not sure if this is an option for you.

**Comment by dzsoga** [comment]
Thank you kindly for our answer! You are right, there are 6 Majorana neutrinos in the particle spectrum. It is a good start for me, I wanted to neglect the mixing in the neutrino sector in the first place.

**Comment by Expander** [comment]
Good that this is resolved! :)

I guess you'd now like to modify the SARAH model file to neglect the mixing and re-generate a FlexibleSUSY spectrum generator. If you stumble upon more issues, please let us know! :)
