### ISSUE TITLE
Order in pseudoscalar mixing matrix

### ISSUE THREAD

**Issue by wkotlarski** [FlexibleSUSY/FlexibleSUSY#545]
@Expander, this is the mixing matrix for a model with 4 pseudoscalar Higgses
```
ZA =          -0          -0          -1 -1.2723e-05
 -0.0928685    0.995678           0           0
   0.995678   0.0928685           0           0
          0           0  1.2723e-05          -1
```
The basis is: $(H_d, H_u, S, T)$. Row 1 corresponds to a singlet with mass of ~60 GeV. The basis is as defined in SARAH's `MRSSM .m` file. The problem is that the masses of pseudoscalars are reordered. So in the decay calculation we expect that the 60 GeV singlet will have index 1 (in C++ counting). This means we are taking index 1 in it's couplings (they are proportional to `ZA[1, _]`). But this is wrong. Because the mixing matrices are not reordered. This causes FS to report that the singlet happily decays to SM fermions as follows
```
DECAY        36     2.27147254E-03   # Ah(2) decays
     6.07301649E-01   2          -5         5  # BR(Ah(2) -> barFd(3) Fd(3))
     2.33688515E-01   2          22        22  # BR(Ah(2) -> VP VP)
     6.91614792E-02   2          21        21  # BR(Ah(2) -> VG VG)
     5.84869588E-02   2         -15        15  # BR(Ah(2) -> barFe(3) Fe(3))
     3.08526491E-02   2          -4         4  # BR(Ah(2) -> barFu(2) Fu(2))
     2.61383513E-04   2          -3         3  # BR(Ah(2) -> barFd(2) Fd(2))
     2.07068149E-04   2         -13        13  # BR(Ah(2) -> barFe(2) Fe(2))
     3.96120148E-05   2    -1000022   1000022  # BR(Ah(2) -> barChi(1) Chi(1))
     5.20453379E-07   2          -1         1  # BR(Ah(2) -> barFd(1) Fd(1))
     1.60187934E-07   2          -2         2  # BR(Ah(2) -> barFu(1) Fu(1))
     4.84337120E-09   2         -11        11  # BR(Ah(2) -> barFe(1) Fe(1))
```

**Comment by Expander** [comment]
Just to make sure I understand the issue correctly: The MRSSM SARAH model file uses parts of SARAH's general `particles.m`, wher we have the line
~~~
     {{   Description -> "Z-Boson",
                 PDG -> {23},
                 PDG.IX ->{122000001},
                 Width -> 2.4952, 
                 Mass -> 91.1876,
                 FeynArtsNr -> 2,
                 ElectricCharge -> 0,
                 Goldstone -> Ah[{1}],
                 LaTeX -> "Z",
                 OutputName -> "Z" }}, 
~~~
which says that the Goldstone boson, that corresponds to the Z boson, shall be at the position 1 (in Mathematica index convention) in the CP-odd Higgs multiplet `Ah`.

FS generates the following functions which do this reordering:
~~~.cpp
/**
 * reorders DRbar masses so that golstones are placed at the index
 * specified in the model files definition of the associated
 * gauge boson (see Z-boson definition in default particles.m file
 * in the Models directory of your SARAH distribution for example)
 */
void CLASSNAME::reorder_DRbar_masses()
{
   move_goldstone_to(0, MVZ, MAh, ZA);
   move_goldstone_to(0, MVWm, MHpm, ZP);
}

/**
 * reorders pole masses so that golstones are placed at the index
 * specified in the model files definition of the associated
 * gauge boson (see Z-boson definition in default particles.m file
 * in the Models directory of your SARAH distribution for example)
 */
void CLASSNAME::reorder_pole_masses()
{
   move_goldstone_to(0, MVZ, PHYSICAL(MAh), PHYSICAL(ZA));
   move_goldstone_to(0, MVWm, PHYSICAL(MHpm), PHYSICAL(ZP));
}
~~~
The functions reorder the mass multiplet and the mixing matrices consistently (if there is no bug :) ). When `calculate_spectrum()` has been called, these functions are called and thus the ordering should be such that the Goldstone boson with $m_{G^0}\approx 91$ GeV should be first in the multiplet and the mixing matrices are reordered accordingly.

If I understand you correctly, the mass reordering happens as described, right? I.e. the ~60GeV pseudoscalar is at the 2nd position in the multiplet (index 2 in Mathematica's index convention, index 1 in C++ convention). Are you saying that the corresponding mixing matrices are not reordered properly?

**Comment by wkotlarski** [comment]
Yes. This mixing matrix 
```
ZA =          -0          -0          -1 -1.2723e-05
 -0.0928685    0.995678           0           0
   0.995678   0.0928685           0           0
          0           0  1.2723e-05          -1
```
looks like the 60 GeV state is moved to position 0. Those two lines
```
 -0.0928685    0.995678           0           0
   0.995678   0.0928685           0           0
```
are the $H_d$ - $H_u$ mixing. So the Goldstone is there.

**Comment by Expander** [comment]
Interesting. :) Could you please paste an SLHA example input file here, that I can use to reproduce the issue?

**Comment by wkotlarski** [comment]
[BMP1.in.txt](https://github.com/FlexibleSUSY/FlexibleSUSY/files/11445456/BMP1.in.txt)

**Comment by Expander** [comment]
Thanks! Is this a model file for the `MRSSM` implemented in FS? (Not the `MRSSM2`?)

**Comment by wkotlarski** [comment]
It's MRSSM2. One extra remark: please look at the mixing matrix `ZA` used in function `calculate_Ah_decays` in `MRSSM2_decays.cpp`. I think that in other places this `ZA` is fine. Maybe it has something to do with the decoupling scheme we use there?

**Comment by wkotlarski** [comment]
I start to understand what's going on. The pole mixing matrix is ordered as it should
```
ZA =   -0.0919114     0.995767  1.14022e-05 -7.35237e-07
 1.72431e-06 -1.12915e-05            1  1.37113e-05
    0.995767    0.0919114 -6.79204e-07  1.27986e-06
 1.34205e-06 -6.14645e-07  1.37113e-05           -1
```
But the tree-level one that is used in vertices is not
```
ZA =           -0           -0           -1 -1.27309e-05
  -0.0928053     0.995684            0            0
    0.995684    0.0928053            0            0
           0            0  1.27309e-05           -1
```
Adding to `calculate_Ah_decays` statement `model.reorder_DRbar_masses();` does fix the model. But construction of decoupling scheme discards the order again. I cannot call `reorder_tree_level_masses()` on `dec_model` because it's private. I can add it directly to `_mass_eigenstates_decoupling_scheme::fill_from` and than everything works as intended.

**Comment by wkotlarski** [comment]
@Expander, we have to add `reorder_DRbar_masses()` call somewhere. I think a nicer solution would be to expose it in `<model>_mass_eigenstates_decoupling_scheme` and call it from `calculate_*_decays`. What do you think?

**Comment by Expander** [comment]
Sorry for the delay. I now ran your input point and could reproduce your results.

**Comment by Expander** [comment]
I think I've found the problem. I'll create a PR for your to review. :)
