### ISSUE TITLE
missing HMIX entry in the MRSSM

### ISSUE THREAD

**Issue by wkotlarski** [FlexibleSUSY/FlexibleSUSY#565]
@Expander, `micrOMEGAs` fails with our `MRSSM2` spectrum. That's because `CalcHEP` model tries to read `betaH` from entry 10 in the `HMIX` block. Do you know why we don't add it? All other entries in this block are present. I'm guessing that has something to do with the fact that `betaH` is not defined in `MRSSM`\`s `parameters.s`. It's part of SARAH\`s global `parameters.m`.  If this is an expected behaviour that should not be fixed, then I'll submit a change to the model where we override `HMIX` block  with the block with an extra entry 10.

**Comment by Expander** [comment]
I have never considered to add all parameters defined in SARAH's `parameters.m` files, because I was afraid that some of the global definitions may not be applicable to any model and thus may lead to problems.

If you'd submit a PR to simply fill entry `HMIX[10]` for the `MRSSM2` model, I think this would be best. :)

**Comment by wkotlarski** [comment]
SARAH does it somehow in a clever way such that only relevant parameters appear. That's why in the `MRSSM2` there's only one extra entry. But for my application I can just add it by hand. I'll make a PR.
